const { MessageEmbed } = require("discord.js");

const achievements = [{
        id: 'achev1',
        name: 'Chatterbox',
        description: 'Send 100 Messages',
    },
    {
        id: 'achev2',
        name: 'Talker',
        description: 'Send 1000 Messages',
    },
    {
        id: 'achev3',
        name: 'Log Jockey',
        description: 'Send 100000 Messages',
    },
    {
        id: 'achev4',
        name: 'Chatty Cathy',
        description: 'Send 1000000 Messages',
    },
    {
        id: 'achev5',
        name: 'Silver Tongued Devil',
        description: 'Talk for 1 hour',
    },
    {
        id: 'achev6',
        name: 'Golden Tongued Devil',
        description: 'Talk for 10 hours',
    },
    {
        id: 'achev7',
        name: 'Platinum Tongued Devil',
        description: 'Talk for 100 hours',
    },
    {
        id: 'achev8',
        name: 'Diamond Tongued Devil',
        description: 'Talk for 1000 hours',
    },
    {
        id: 'achev9',
        name: 'Event Winner',
        description: 'Win an Event',
    },
    {
        id: 'achev10',
        name: 'Event Champion',
        description: 'Win 5 Events',
    },
    {
        id: 'achev11',
        name: 'Event Legend',
        description: 'Win 10 Events',
    },
    {
        id: 'achev12',
        name: 'Meme Master',
        description: 'Be voted Meme Master',
    },
    {
        id: 'achev13',
        name: 'Content Creator',
        description: 'Be voted Content Creator',
    },
];

module.exports = {
    name: 'achievements',
    aliases: ['av'],
    description: 'View your achievements or somebody else\'s',
    examples: ['$achievements,View your achievements',
        '$achievements @Ms6RB.,View @Ms6RB.#1101\'s achievements'
    ],

    async execute(client, msg, args) {

        let data;

        try {
            const member = msg.mentions.users.first();

            if (member) {
                if (member.bot) return msg.reply('bot?');
                data = await getData(client.query, member.id);
            } else if (!args[0] || args[0] == undefined) {
                data = await getData(client.query, msg.author.id);
            } else return msg.reply('``$$achievements [mention]``');

            data = filterObject(data);


            const embed = new MessageEmbed()
                .setColor('#000033')
                .setTitle('Achievements')
                .setDescription('Here is a list of all the achievements you have earned.');

            let fields = [];
            for (const achievement of achievements) {
                const achieved = data[achievement.id] > 0;
                const name = achievement.name;
                fields.push({
                    name,
                    value: achieved ? 'Achieved' : 'Not achieved'
                })
                
            }

            embed.addFields(fields);
            embed.setTimestamp()
            embed.setFooter('Generated by Bard - Awelaw');

            msg.channel.send({embeds: [embed]});

            return;
        } catch (err) {
            console.log(err);
        }

    }
};


async function getData(query, userID) {
    const data = await query(`SELECT * from achievements where id = "${userID}"`);
    return data[0];
}


function filterObject(obj) {
    const filteredObj = {};
  
    for (let key in obj) {
      if (obj.hasOwnProperty(key) && key.includes("achev")) {
        filteredObj[key] = obj[key];
      }
    }
  
    return filteredObj;
}